class WelcomeError(Exception):
    pass

class AuthError(Exception):
    pass
